/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class HRManager extends javax.swing.JFrame {

    /**
     * Creates new form HRManager
     */
    public HRManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HRManager = new javax.swing.JPanel();
        Options = new javax.swing.JLabel();
        AddDept = new javax.swing.JButton();
        AddEmp = new javax.swing.JButton();
        ManageDept = new javax.swing.JButton();
        ManageEmp = new javax.swing.JButton();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HRManager.setBackground(new java.awt.Color(255, 255, 255));

        Options.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Options.setForeground(new java.awt.Color(0, 102, 102));
        Options.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Options.setText("HR Manager Home");

        AddDept.setBackground(new java.awt.Color(0, 102, 102));
        AddDept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddDept.setForeground(new java.awt.Color(255, 255, 255));
        AddDept.setText("Add Department");
        AddDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDeptActionPerformed(evt);
            }
        });

        AddEmp.setBackground(new java.awt.Color(0, 102, 102));
        AddEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddEmp.setForeground(new java.awt.Color(255, 255, 255));
        AddEmp.setText("Add Employee");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });

        ManageDept.setBackground(new java.awt.Color(0, 102, 102));
        ManageDept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageDept.setForeground(new java.awt.Color(255, 255, 255));
        ManageDept.setText("Manage Department Details");
        ManageDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDeptActionPerformed(evt);
            }
        });

        ManageEmp.setBackground(new java.awt.Color(0, 102, 102));
        ManageEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageEmp.setForeground(new java.awt.Color(255, 255, 255));
        ManageEmp.setText("Manage Employee Details");
        ManageEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmpActionPerformed(evt);
            }
        });

        BACK.setText("<");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HRManagerLayout = new javax.swing.GroupLayout(HRManager);
        HRManager.setLayout(HRManagerLayout);
        HRManagerLayout.setHorizontalGroup(
            HRManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HRManagerLayout.createSequentialGroup()
                .addGroup(HRManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HRManagerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(HRManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddDept, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageDept, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HRManagerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BACK)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        HRManagerLayout.setVerticalGroup(
            HRManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Options, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddDept)
                .addGap(33, 33, 33)
                .addComponent(AddEmp)
                .addGap(34, 34, 34)
                .addComponent(ManageDept)
                .addGap(36, 36, 36)
                .addComponent(ManageEmp)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HRManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HRManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDeptActionPerformed
        {setVisible(false);
            AddDpt department=new AddDpt();
            department.setVisible(true);
        }
    }//GEN-LAST:event_AddDeptActionPerformed

    private void ManageDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDeptActionPerformed
        {setVisible(false);
            ManageDpt department=new ManageDpt();
            department.setVisible(true);
        }
    }//GEN-LAST:event_ManageDeptActionPerformed

    private void ManageEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmpActionPerformed
        {setVisible (false);
        ManageEmp employee=new ManageEmp ();
        employee.setVisible (true);
        }
    }//GEN-LAST:event_ManageEmpActionPerformed

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
        {setVisible(false);
            AddEmp employee=new AddEmp();
            employee.setVisible(true);
        }
    }//GEN-LAST:event_AddEmpActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
       Login java  = new Login();
            java.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDept;
    private javax.swing.JButton AddEmp;
    private javax.swing.JButton BACK;
    private javax.swing.JPanel HRManager;
    private javax.swing.JButton ManageDept;
    private javax.swing.JButton ManageEmp;
    private javax.swing.JLabel Options;
    // End of variables declaration//GEN-END:variables
}
