import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class ManageDpt extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    int usertype;

    /**
     * Creates new form ManageDpt
     */
    public ManageDpt() {
        initComponents();
        try {
    String url = "jdbc:mysql://localhost/oop_assignment";
    String user = "root";
    String password = "";


    conn = DriverManager.getConnection(url, user, password);
    System.out.println("Connected!conn...");
    } catch (Exception ex) {
    System.out.println("Error : " + ex.getMessage());
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageDeptPanel = new javax.swing.JPanel();
        SolidClrPanel = new javax.swing.JPanel();
        DptID = new javax.swing.JLabel();
        DptName = new javax.swing.JLabel();
        DptIDTxt = new javax.swing.JTextField();
        DptNameTxt = new javax.swing.JTextField();
        Designation = new javax.swing.JLabel();
        DesignationTxt = new javax.swing.JTextField();
        Find = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        ManageDept = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DptTable = new javax.swing.JTable();
        ViewAll = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        ClearAll = new javax.swing.JButton();
        ViewDptDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ManageDeptPanel.setBackground(new java.awt.Color(255, 255, 255));
        ManageDeptPanel.setPreferredSize(new java.awt.Dimension(688, 400));

        SolidClrPanel.setBackground(new java.awt.Color(0, 102, 102));

        DptID.setBackground(new java.awt.Color(255, 255, 255));
        DptID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DptID.setForeground(new java.awt.Color(255, 255, 255));
        DptID.setText("Department ID");

        DptName.setBackground(new java.awt.Color(255, 255, 255));
        DptName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DptName.setForeground(new java.awt.Color(255, 255, 255));
        DptName.setText("Department Name");

        Designation.setBackground(new java.awt.Color(255, 255, 255));
        Designation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Designation.setForeground(new java.awt.Color(255, 255, 255));
        Designation.setText("Designation");

        Find.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Find.setForeground(new java.awt.Color(0, 102, 102));
        Find.setText("Find");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(0, 102, 102));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 51, 51));
        Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SolidClrPanelLayout = new javax.swing.GroupLayout(SolidClrPanel);
        SolidClrPanel.setLayout(SolidClrPanelLayout);
        SolidClrPanelLayout.setHorizontalGroup(
            SolidClrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolidClrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SolidClrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolidClrPanelLayout.createSequentialGroup()
                        .addComponent(Find)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reset))
                    .addGroup(SolidClrPanelLayout.createSequentialGroup()
                        .addGroup(SolidClrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DptID)
                            .addComponent(DptName)
                            .addComponent(DptIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DptNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Designation)
                            .addComponent(DesignationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolidClrPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Delete)))
                .addContainerGap())
        );
        SolidClrPanelLayout.setVerticalGroup(
            SolidClrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolidClrPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(DptID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DptIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DptName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DptNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Designation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesignationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(SolidClrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Find, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        ManageDept.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ManageDept.setForeground(new java.awt.Color(0, 102, 102));
        ManageDept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageDept.setText("Manage Department Details");
        ManageDept.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ManageDept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageDept.setPreferredSize(new java.awt.Dimension(255, 32));
        ManageDept.setVerifyInputWhenFocusTarget(false);

        DptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Department ID", "Department Name", "Designation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DptTable.setGridColor(new java.awt.Color(255, 255, 255));
        DptTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(DptTable);

        ViewAll.setBackground(new java.awt.Color(0, 102, 102));
        ViewAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewAll.setForeground(new java.awt.Color(255, 255, 255));
        ViewAll.setText("View All");
        ViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllActionPerformed(evt);
            }
        });

        BACK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        ClearAll.setBackground(new java.awt.Color(255, 51, 51));
        ClearAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearAll.setForeground(new java.awt.Color(255, 255, 255));
        ClearAll.setText("Clear All");
        ClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllActionPerformed(evt);
            }
        });

        ViewDptDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewDptDetails.setForeground(new java.awt.Color(0, 102, 102));
        ViewDptDetails.setText("View Department Details");
        ViewDptDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDptDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageDeptPanelLayout = new javax.swing.GroupLayout(ManageDeptPanel);
        ManageDeptPanel.setLayout(ManageDeptPanelLayout);
        ManageDeptPanelLayout.setHorizontalGroup(
            ManageDeptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDeptPanelLayout.createSequentialGroup()
                .addComponent(SolidClrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManageDeptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(ManageDept, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ManageDeptPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ManageDeptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BACK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ViewDptDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ManageDeptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearAll)
                            .addComponent(ViewAll, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        ManageDeptPanelLayout.setVerticalGroup(
            ManageDeptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SolidClrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ManageDeptPanelLayout.createSequentialGroup()
                .addComponent(ManageDept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ManageDeptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BACK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ManageDeptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageDeptPanelLayout.createSequentialGroup()
                        .addComponent(ViewDptDetails)
                        .addGap(2, 2, 2)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageDeptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageDeptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
    HRManager java  = new HRManager();
            java.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_BACKActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
    DptIDTxt.setText("");
    DptNameTxt.setText("");
    DesignationTxt.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
       try{
    int p = JOptionPane.showConfirmDialog(null,"Do you want to detele the selected record?","Delete",JOptionPane.YES_NO_OPTION);
    if(p==0){            
          String DepartmentID = DptIDTxt.getText();       
          String sql = "DELETE FROM department WHERE DepartmentID=?";
          pst = conn.prepareStatement(sql);
          
          pst.setString (1,DepartmentID);
          
         pst.execute();
         JOptionPane.showMessageDialog(null, "Department Record Deleted");
                
                }   
            } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllActionPerformed
       try{
           String sql="SELECT * FROM department";
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           DefaultTableModel model=(DefaultTableModel)DptTable.getModel();
           model.setRowCount(0);
           if(rs.isBeforeFirst()){
               while(rs.next()){
                   model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
               }
           }else{
              JOptionPane.showMessageDialog(this, "Departments Record Not Found!");   
           }
        }catch (Exception ex){
            System.out.println("Error : " + ex.getMessage());            
        }

    }//GEN-LAST:event_ViewAllActionPerformed

    private void ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllActionPerformed
     DefaultTableModel model = (DefaultTableModel) DptTable.getModel();
    model.setRowCount(0);
    }//GEN-LAST:event_ClearAllActionPerformed

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        try{
            String DepartmentID =DptIDTxt.getText();

            String sql = "SELECT * FROM department WHERE DepartmentID =?";

            pst = conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            pst.setString(1, DepartmentID);

            rs = pst.executeQuery();
            if(rs.isBeforeFirst()){

                rs.first();
                DptIDTxt.setText(rs.getString(1));
                DptNameTxt.setText(rs.getString(2));
                DesignationTxt.setText (rs.getString(3));
                
                JOptionPane.showMessageDialog(this, "Department Record Found!" );
                
                DefaultTableModel model = (DefaultTableModel) DptTable.getModel();
            model.setRowCount(0); // Clear existing rows
            model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
                
                

            }else{
                JOptionPane.showMessageDialog(this, "Department Not Found!" );
                
          
            }

        } catch (HeadlessException | SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_FindActionPerformed

    private void ViewDptDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDptDetailsActionPerformed
        ViewDpt java  = new ViewDpt();
            java.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_ViewDptDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDpt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Designation;
    private javax.swing.JTextField DesignationTxt;
    private javax.swing.JLabel DptID;
    private javax.swing.JTextField DptIDTxt;
    private javax.swing.JLabel DptName;
    private javax.swing.JTextField DptNameTxt;
    private javax.swing.JTable DptTable;
    private javax.swing.JButton Find;
    private javax.swing.JLabel ManageDept;
    private javax.swing.JPanel ManageDeptPanel;
    private javax.swing.JButton Reset;
    private javax.swing.JPanel SolidClrPanel;
    private javax.swing.JButton ViewAll;
    private javax.swing.JButton ViewDptDetails;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
