import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class ManageEmp extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    /**
    /**
     * Creates new form ManageEmp
     */
    public ManageEmp() {
        initComponents();
        try {
    String url = "jdbc:mysql://localhost/oop_assignment";
    String user = "root";
    String password = "";


    conn = DriverManager.getConnection(url, user, password);
    System.out.println("Connected!conn...");
    } catch (Exception ex) {
    System.out.println("Error : " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageEmpPanel = new javax.swing.JPanel();
        DetailsPanel = new javax.swing.JPanel();
        ManageEmp = new javax.swing.JLabel();
        EmpID = new javax.swing.JLabel();
        EmpIDTxt = new javax.swing.JTextField();
        EmpName = new javax.swing.JLabel();
        EmpNameTxt = new javax.swing.JTextField();
        Dpt = new javax.swing.JLabel();
        DptTxt = new javax.swing.JTextField();
        Designation = new javax.swing.JLabel();
        DesignationTxt = new javax.swing.JTextField();
        EPFNo = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        ContactNo = new javax.swing.JLabel();
        EPFNOTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        DOBTxt = new javax.swing.JTextField();
        CNOTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpTable = new javax.swing.JTable();
        ViewAll = new javax.swing.JButton();
        ClearAll = new javax.swing.JButton();
        FindPanel = new javax.swing.JPanel();
        FIND = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        ViewEmpDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ManageEmpPanel.setBackground(new java.awt.Color(255, 255, 255));

        DetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        ManageEmp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ManageEmp.setForeground(new java.awt.Color(0, 102, 102));
        ManageEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageEmp.setText("Manage Employee Details");

        EmpID.setBackground(new java.awt.Color(255, 255, 255));
        EmpID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmpID.setText("Employee ID");

        EmpName.setBackground(new java.awt.Color(255, 255, 255));
        EmpName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmpName.setText("Employee Name");

        Dpt.setBackground(new java.awt.Color(255, 255, 255));
        Dpt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dpt.setText("Department");

        Designation.setBackground(new java.awt.Color(255, 255, 255));
        Designation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Designation.setText("Designation");

        EPFNo.setBackground(new java.awt.Color(255, 255, 255));
        EPFNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EPFNo.setText("EPF No.");

        Address.setBackground(new java.awt.Color(255, 255, 255));
        Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Address.setText("Address");

        DOB.setBackground(new java.awt.Color(255, 255, 255));
        DOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DOB.setText("DOB");

        ContactNo.setBackground(new java.awt.Color(255, 255, 255));
        ContactNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNo.setText("Contact No");

        javax.swing.GroupLayout DetailsPanelLayout = new javax.swing.GroupLayout(DetailsPanel);
        DetailsPanel.setLayout(DetailsPanelLayout);
        DetailsPanelLayout.setHorizontalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(ManageEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPFNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EPFNo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpName)
                            .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dpt)
                            .addComponent(DptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Designation)
                            .addComponent(DesignationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        DetailsPanelLayout.setVerticalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addComponent(ManageEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addComponent(Designation)
                        .addGap(65, 65, 65))
                    .addGroup(DetailsPanelLayout.createSequentialGroup()
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpID)
                            .addComponent(EmpName)
                            .addComponent(Dpt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DesignationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EmpIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmpNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)))
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactNo)
                    .addComponent(DOB)
                    .addComponent(Address)
                    .addComponent(EPFNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EPFNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        EmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Department", "Designation", "EPF No.", "Address", "DOB", "Contact No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EmpTable);

        ViewAll.setBackground(new java.awt.Color(0, 102, 102));
        ViewAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewAll.setForeground(new java.awt.Color(255, 255, 255));
        ViewAll.setText("View All");
        ViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllActionPerformed(evt);
            }
        });

        ClearAll.setBackground(new java.awt.Color(255, 51, 51));
        ClearAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearAll.setForeground(new java.awt.Color(255, 255, 255));
        ClearAll.setText("Clear All");
        ClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllActionPerformed(evt);
            }
        });

        FindPanel.setBackground(new java.awt.Color(0, 102, 102));

        FIND.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FIND.setForeground(new java.awt.Color(0, 102, 102));
        FIND.setText("Find");
        FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINDActionPerformed(evt);
            }
        });

        DELETE.setBackground(new java.awt.Color(255, 51, 51));
        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("Delete");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        RESET.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RESET.setForeground(new java.awt.Color(0, 102, 102));
        RESET.setText("Reset");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FindPanelLayout = new javax.swing.GroupLayout(FindPanel);
        FindPanel.setLayout(FindPanelLayout);
        FindPanelLayout.setHorizontalGroup(
            FindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(FindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DELETE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FIND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RESET, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        FindPanelLayout.setVerticalGroup(
            FindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FIND, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BACK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        ViewEmpDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewEmpDetails.setForeground(new java.awt.Color(0, 102, 102));
        ViewEmpDetails.setText("View Employee Details");
        ViewEmpDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmpDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageEmpPanelLayout = new javax.swing.GroupLayout(ManageEmpPanel);
        ManageEmpPanel.setLayout(ManageEmpPanelLayout);
        ManageEmpPanelLayout.setHorizontalGroup(
            ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageEmpPanelLayout.createSequentialGroup()
                .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FindPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(ManageEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(ManageEmpPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BACK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ViewEmpDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearAll)
                            .addComponent(ViewAll, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        ManageEmpPanelLayout.setVerticalGroup(
            ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageEmpPanelLayout.createSequentialGroup()
                .addGroup(ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FindPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ManageEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewEmpDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
                EmpIDTxt.setText("");
                EmpNameTxt.setText("");
                DptTxt.setText ("");
                DesignationTxt.setText("");
                EPFNOTxt.setText("");
                AddressTxt.setText ("");
                DOBTxt.setText ("");
                CNOTxt.setText("");
    }//GEN-LAST:event_RESETActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
      try{
    int p = JOptionPane.showConfirmDialog(null,"Do you want to detele the selected record?","Delete",JOptionPane.YES_NO_OPTION);
    if(p==0){            
          String EmpID = EmpIDTxt.getText();       
          String sql = "DELETE FROM employee WHERE EmployeeID=?";
          pst = conn.prepareStatement(sql);
          
          pst.setString (1,EmpID);
          
         pst.execute();
         JOptionPane.showMessageDialog(null, "Employee Record Deleted");
                
                }   
            } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_DELETEActionPerformed

    private void ViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllActionPerformed
        try{
           String sql="SELECT * FROM employee";
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           DefaultTableModel model=(DefaultTableModel)EmpTable.getModel();
           model.setRowCount(0);
           if(rs.isBeforeFirst()){
               while(rs.next()){
                   model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)
                           ,rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)});
               }
           }else{
              JOptionPane.showMessageDialog(this, "Employee Record Not Found!");   
           }
        }catch (Exception ex){
            System.out.println("Error : " + ex.getMessage());            
        }
    }//GEN-LAST:event_ViewAllActionPerformed

    private void ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllActionPerformed
    DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
    model.setRowCount(0);
    }//GEN-LAST:event_ClearAllActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
    HRManager java  = new HRManager();
            java.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_BACKActionPerformed

    private void FINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINDActionPerformed
        try{
            String EmployeeID =EmpIDTxt.getText();

            String sql = "SELECT * FROM employee WHERE EmployeeID =?";

            pst = conn.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            pst.setString(1, EmployeeID);

            rs = pst.executeQuery();
            if(rs.isBeforeFirst()){

                rs.first();
                EmpIDTxt.setText(rs.getString(1));
                EmpNameTxt.setText(rs.getString(2));
                DptTxt.setText (rs.getString(3));
                DesignationTxt.setText(rs.getString(4));
                EPFNOTxt.setText(rs.getString(6));
                AddressTxt.setText (rs.getString(7));
                DOBTxt.setText (rs.getString(5));
                CNOTxt.setText(rs.getString(8));
                
                JOptionPane.showMessageDialog(this, "Employee record found!");
                
                DefaultTableModel model = (DefaultTableModel) EmpTable.getModel();
            model.setRowCount(0); // Clear existing rows
            model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), 
                rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)});

            }else{
                JOptionPane.showMessageDialog(this, "Employee Not Found!" );
            }

        } catch (HeadlessException | SQLException ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_FINDActionPerformed

    private void ViewEmpDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmpDetailsActionPerformed
        ViewEmp java  = new ViewEmp();
            java.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_ViewEmpDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JButton BACK;
    private javax.swing.JTextField CNOTxt;
    private javax.swing.JButton ClearAll;
    private javax.swing.JLabel ContactNo;
    private javax.swing.JButton DELETE;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField DOBTxt;
    private javax.swing.JLabel Designation;
    private javax.swing.JTextField DesignationTxt;
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JLabel Dpt;
    private javax.swing.JTextField DptTxt;
    private javax.swing.JTextField EPFNOTxt;
    private javax.swing.JLabel EPFNo;
    private javax.swing.JLabel EmpID;
    private javax.swing.JTextField EmpIDTxt;
    private javax.swing.JLabel EmpName;
    private javax.swing.JTextField EmpNameTxt;
    private javax.swing.JTable EmpTable;
    private javax.swing.JButton FIND;
    private javax.swing.JPanel FindPanel;
    private javax.swing.JLabel ManageEmp;
    private javax.swing.JPanel ManageEmpPanel;
    private javax.swing.JButton RESET;
    private javax.swing.JButton ViewAll;
    private javax.swing.JButton ViewEmpDetails;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
